"held_out_codes":
- "000000800429"
- "000001500010"
- "000001500007"
- "000000800133"
- "000002000103"
- "000004000001"
- "000002000102"
- "000001000046"
- "000000500200"
- "000000500016"
- "000000800412"
- "000009000003"
- "000000800146"
- "000002600001"
- "000000500017"
- "000002600003"
- "000002600002"
- "000000800217"
- "000000500018"
- "000000500022"
- "000001200000"
- "000000800057"
- "000000800007"
"percentile": 15.0
"min_count": 1
"total_codes": 179
"num_held_out": 23
"exams_root_sha": "70d9e05b6401"
"generated": "2025-11-26T14:35:46+00:00"
