cut_dates:
  train_val: '2017-04-10'
  val_test: '2020-05-11'
statistics:
  total_exams: 998094
  train_ssl_count: 698633
  val_ssl_count: 149700
  test_future_count: 149761
  train_percentage: 70.0
  val_percentage: 15.0
  test_percentage: 15.0
generated_at: '2025-05-07 13:44:33'
source_data_hash: 0388feb4a1b7d90208b2cc8a70102215c69ffecc7825a205435c90db290047e6
random_seed: 0
